In [1]:
pip install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in c:\users\anton\anaconda3\lib\site-packages (4.11.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\anton\anaconda3\lib\site-packages (from beautifulsoup4) (2.3.1)
Note: you may need to restart the kernel to use updated packages.

In [210]:
import requests
from bs4 import BeautifulSoup
import re
import pandas as pd
import numpy as np

In [10]:

# Header of info to be sent to websites accessed without API
header = {  'Names':'Anton Maach-Møller', 'Position':'Students at KU', 'Email':'hfp710@alumni.ku.dk', 
            'Phone':'0045 22462276', 'Description':'Gather list of MPs for research project at KU'}

In [165]:
website_url = requests.get('https://en.wikipedia.org/wiki/2020_United_States_presidential_election', headers={'name':'Anton Maach-Møller','email':'hfp710@econ.ku.dk'})

soup = BeautifulSoup(website_url.text,'lxml')

 
#cite_ref-FEC_5-3 Results_by_state

In [205]:
#my_table = soup.find_all('table', {"class": "wikitable", "class": "sortable"})

table_soup=soup.find_all('table')
filtered_table_soup = [table for table in table_soup if table.caption is not None]

required_tabel = None
'''
for table in filtered_table_soup:
    if str(table.caption.string).strip() == "Results by State" :
        required_table = table
        break
        
print(required_table)
'''

'\nfor table in filtered_table_soup:\n    if str(table.caption.string).strip() == "Results by State" :\n        required_table = table\n        break\n        \nprint(required_table)\n'

In [180]:
columns_html = my_table.find_all('th')
# Extract the text
columns = [col.text for col in columns_html] #Use a list comprehension to make extract the text (If you have used a for loop instead, it is also just fine!)
### END SOLUTION

columns

['Donald Trump vs. Joe Biden\n',
 'Source of poll aggregation\n',
 'Dates administered\n',
 'Dates updated\n',
 'Joe Biden\n',
 'Donald Trump\n',
 'Other/Undecided[j]\n',
 'Margin\n']

In [127]:
# drop the unwanted columns
data = df.drop(["Rank", "Population(2001)"], axis=1)
# rename columns for ease
data = data.rename(columns={"State or union territory": "State","Population(2011)[3]": "Population"})
print(data.head())

        City Population        State
0     Mumbai   12442373  Maharashtra
1      Delhi   11007835        Delhi
2  Bangalore    8425970    Karnataka
3  Hyderabad    6809970    Telangana
4  Ahmedabad    5570585      Gujarat

In [151]:
pip install Wikipedia-API

Collecting Wikipedia-API
  Downloading Wikipedia-API-0.5.4.tar.gz (18 kB)
Requirement already satisfied: requests in c:\users\anton\anaconda3\lib\site-packages (from Wikipedia-API) (2.27.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\anton\anaconda3\lib\site-packages (from requests->Wikipedia-API) (1.26.9)
Requirement already satisfied: idna<4,>=2.5 in c:\users\anton\anaconda3\lib\site-packages (from requests->Wikipedia-API) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\anton\anaconda3\lib\site-packages (from requests->Wikipedia-API) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\anton\anaconda3\lib\site-packages (from requests->Wikipedia-API) (2.0.4)
Building wheels for collected packages: Wikipedia-API
  Building wheel for Wikipedia-API (setup.py): started
  Building wheel for Wikipedia-API (setup.py): finished with status 'done'
  Created wheel for Wikipedia-API: filename=Wikipedia_API-0.5.4-py3-none-any.whl size=13476 sha256=d42aa3454db25797adca2292ee81df735fce5e917090f22c268975990ef7fcae
  Stored in directory: c:\users\anton\appdata\local\pip\cache\wheels\c7\cf\1a\c300428dd51654cdadc921abdff75acaa7cc80b7151a2f0695
Successfully built Wikipedia-API
Installing collected packages: Wikipedia-API
Successfully installed Wikipedia-API-0.5.4
Note: you may need to restart the kernel to use updated packages.

In [372]:
#Start by importing the website where we want to extract the data from

dfs = pd.read_html('https://en.wikipedia.org/wiki/2020_United_States_presidential_election')

In [373]:
#seeing that the table we want is the nr19 therefore we extract that
table_stat = dfs[19]
table_stat.head(5)

  State ordistrict Biden/HarrisDemocratic             Trump/PenceRepublican  \
  State ordistrict                  Votes       %  EV                 Votes
0            Alab.                 849624  36.57%   –               1441170
1           Alaska                 153778  42.77%   –                189951
2          Arizona                1672143  49.36%  11               1661686
3             Ark.                 423932  34.78%   –                760647
4           Calif.               11110250  63.48%  55               6006429

             Jorgensen/CohenLibertarian           Hawkins/WalkerGreen         \
        % EV                      Votes      % EV               Votes      %
0  62.03%  9                      25176  1.08%  –                 [m]    [m]
1  52.83%  3                       8897  2.47%  –                 [n]    [n]
2  49.06%  –                      51465  1.52%  –                1557  0.05%
3  62.40%  6                      13133  1.08%  –                2980  0.24%
4  34.32%  –                     187895  1.07%  –               81029  0.46%

      Others              Margin          Marginswing[l] Totalvotes
  EV   Votes      % EV     Votes        %              % Totalvotes
0  –    7312  0.31%  –  −591,546  −25.46%          2.27%    2323282
1  –    6904  1.92%  –   −36,173  −10.06%          4.67%     359530
2  –     475  0.01%  –     10457    0.31%          3.81%    3387326
3  –   18377  1.51%  –  −336,715  −27.62%         −0.70%    1219069
4  –  115278  0.66%  –   5103821   29.16%         −0.95%   17500881

In [374]:
#from the above we see that there are 2 type of headers. We want to deal with this, therefore we put the two columns together 
#by f-string formatting 
table_stat.columns = [f'{i}{j}' for i, j in table_stat.columns]

In [375]:
table_stat.head(5)

,State ordistrictState ordistrict,Biden/HarrisDemocraticVotes,Biden/HarrisDemocratic%,Biden/HarrisDemocraticEV,Trump/PenceRepublicanVotes,Trump/PenceRepublican%,Trump/PenceRepublicanEV,Jorgensen/CohenLibertarianVotes,Jorgensen/CohenLibertarian%,Jorgensen/CohenLibertarianEV,Hawkins/WalkerGreenVotes,Hawkins/WalkerGreen%,Hawkins/WalkerGreenEV,OthersVotes,Others%,OthersEV,MarginVotes,Margin%,Marginswing[l]%,TotalvotesTotalvotes
0,Alab.,849624,36.57%,–,1441170,62.03%,9,25176,1.08%,–,[m],[m],–,7312,0.31%,–,"−591,546",−25.46%,2.27%,2323282
1,Alaska,153778,42.77%,–,189951,52.83%,3,8897,2.47%,–,[n],[n],–,6904,1.92%,–,"−36,173",−10.06%,4.67%,359530
2,Arizona,1672143,49.36%,11,1661686,49.06%,–,51465,1.52%,–,1557,0.05%,–,475,0.01%,–,10457,0.31%,3.81%,3387326
3,Ark.,423932,34.78%,–,760647,62.40%,6,13133,1.08%,–,2980,0.24%,–,18377,1.51%,–,"−336,715",−27.62%,−0.70%,1219069
4,Calif.,11110250,63.48%,55,6006429,34.32%,–,187895,1.07%,–,81029,0.46%,–,115278,0.66%,–,5103821,29.16%,−0.95%,17500881

In [376]:
#then we drop the columns we are not interested in, since we only want to compare Democrats and Republicans
table_stat1= table_stat.drop(table_stat.columns[[3, 6]], axis=1)
table_stat1.head(4)

,State ordistrictState ordistrict,Biden/HarrisDemocraticVotes,Biden/HarrisDemocratic%,Trump/PenceRepublicanVotes,Trump/PenceRepublican%,Jorgensen/CohenLibertarianVotes,Jorgensen/CohenLibertarian%,Jorgensen/CohenLibertarianEV,Hawkins/WalkerGreenVotes,Hawkins/WalkerGreen%,Hawkins/WalkerGreenEV,OthersVotes,Others%,OthersEV,MarginVotes,Margin%,Marginswing[l]%,TotalvotesTotalvotes
0,Alab.,849624,36.57%,1441170,62.03%,25176,1.08%,–,[m],[m],–,7312,0.31%,–,"−591,546",−25.46%,2.27%,2323282
1,Alaska,153778,42.77%,189951,52.83%,8897,2.47%,–,[n],[n],–,6904,1.92%,–,"−36,173",−10.06%,4.67%,359530
2,Arizona,1672143,49.36%,1661686,49.06%,51465,1.52%,–,1557,0.05%,–,475,0.01%,–,10457,0.31%,3.81%,3387326
3,Ark.,423932,34.78%,760647,62.40%,13133,1.08%,–,2980,0.24%,–,18377,1.51%,–,"−336,715",−27.62%,−0.70%,1219069

In [388]:
table_stat2 = table_stat1.drop(table_stat1.iloc[:, 5:18], axis=1)
table_stat2.head(4)

,State ordistrictState ordistrict,Biden/HarrisDemocraticVotes,Biden/HarrisDemocratic%,Trump/PenceRepublicanVotes,Trump/PenceRepublican%
0,Alab.,849624,36.57%,1441170,62.03%
1,Alaska,153778,42.77%,189951,52.83%
2,Arizona,1672143,49.36%,1661686,49.06%
3,Ark.,423932,34.78%,760647,62.40%

In [390]:
#removing extra rows from Maine and Newbraske due to the election rules in these state
table_stat3= table_stat2.drop(table_stat.index[[20, 21,30, 31, 32, 56, 57]], axis=0)

,State ordistrictState ordistrict,Biden/HarrisDemocraticVotes,Biden/HarrisDemocratic%,Trump/PenceRepublicanVotes,Trump/PenceRepublican%
0,Alab.,849624,36.57%,1441170,62.03%
1,Alaska,153778,42.77%,189951,52.83%
2,Arizona,1672143,49.36%,1661686,49.06%
3,Ark.,423932,34.78%,760647,62.40%

In [509]:
# Manually handling the states so their are inlibne with the twitter data. Thereby we can merge the data
table_stat4 = table_stat3.replace(['Alab.','Ark.','Calif.', 'Colo.', 'Conn.', 'Del.', 'D.C.' , 'Ky.', 'La.', 'Maine †', 'Md.', 'Mass.', 'Mich.',
                                  'Minn.', 'Miss.', 'Mo.' , 'Mont.', 'Neb. †', 'Nev.[p]', 'N.H.', 'N.J.[q]' , 'N.M.', 'N.Y.[r]', 'N.C.',
                                  'N.D.', 'Okla.', 'Pa.' , 'R.I.', 'S.C.', 'S.D.', 'Tenn.','Texas[t]', 'Vt.' , 'Va.', 'Wash.', 'W.Va.',
                                  'Wis.', 'Wyo.'], 
                                  ['Alabama','Arkansas','California','Colorado', 'Connecticut', 'Delaware', 'District of Columbia', 'Kentucky',
                                  'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montanna',
                                  'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota',
                                  'Oklahoma', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Vermont',
                                  'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'])
table_stat4.head(4)

,State ordistrictState ordistrict,Biden/HarrisDemocraticVotes,Biden/HarrisDemocratic%,Trump/PenceRepublicanVotes,Trump/PenceRepublican%
0,Alabama,849624,36.57%,1441170,62.03%
1,Alaska,153778,42.77%,189951,52.83%
2,Arizona,1672143,49.36%,1661686,49.06%
3,Arkansas,423932,34.78%,760647,62.40%

In [516]:
#renaming columns to give them more intuitive names for comparison 
table_stat5 = table_stat4.rename(columns = {'State ordistrictState ordistrict':'State', 
                              'Biden/HarrisDemocraticVotes':'Democratic', 'Biden/HarrisDemocratic%':'Democraticpct', 
                              'Trump/PenceRepublicanVotes':'Republican', 'Trump/PenceRepublican%' : 'Republicanpct'})

table_stat5.head(4)

      State Democratic Democraticpct Republican Republicanpct
0   Alabama     849624        36.57%    1441170        62.03%
1    Alaska     153778        42.77%     189951        52.83%
2   Arizona    1672143        49.36%    1661686        49.06%
3  Arkansas     423932        34.78%     760647        62.40%

In [521]:
#Comparing the vote pct to see if the state is either Democratic (blue) or Republican (red) and adding a new collum
comparison_column = np.where(table_stat5["Democraticpct"] > table_stat5["Republicanpct"], 'Blue', 'Red')
table_stat5["Red/Blue State"] = comparison_column

table_stat5.head(5)

        State Democratic Democraticpct Republican Republicanpct Red/Blue State
0     Alabama     849624        36.57%    1441170        62.03%            Red
1      Alaska     153778        42.77%     189951        52.83%            Red
2     Arizona    1672143        49.36%    1661686        49.06%           Blue
3    Arkansas     423932        34.78%     760647        62.40%            Red
4  California   11110250        63.48%    6006429        34.32%           Blue